version: '3'

services:
  driver:
    image: latte164/term-project:latest
    container_name: driver
    ports: 
      - 7050:7050

  jupyter:
    image: jupyter/minimal-notebook
    container_name: jupyter
    ports: 
      - 8000:8000
    environment:
      - JUPYTER_TOKEN=easy
    command: jupyter notebook --allow-root --port=8000 --no-browser --NotebookApp.token='' --NotebookApp.password=''

  spark:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    
  sonar:
    image: sonarqube
    container_name: sonarqube
    ports:
      - 9000:9000

  hadoop:
    image: gelog/hadoop
    container_name: hadoop
    ports:
      - 9050:9050