apiVersion: apps/v1

kind: Deployment

metadata:
  name: spark-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: spark

  template:
    metadata:
      labels:
        component: spark

    spec:
      containers:
        - name: spark
          image: docker.io/bitnami/spark:3
          ports:
            - containerPort: 7077
          environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no